Revert "Works around classpath bug that stopped logging from working"
This reverts commit da7c5f829da5fd6c7a178ffee4f683522879acd6.

Integration tests fail on the following:

```
[zipkin.collector.kafka.KafkaCollector]: Factory method 'kafka' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/Logger
```