Fixes Elasticsearch AWS integration (broken dependency)
We used to transiently include elasticsearch, which had joda dependency.
In order to not conflict with AWS, we excluded joda from AWS. Now, we
don't depend on Elasticsearch anymore so need joda again!

Reported by @mclarke47 as an exception like:

```
Exception in thread "OkHttp Dispatcher" java.lang.NoClassDefFoundError: org/joda/time/ReadableInstant
        at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:151)
```